name: hadenlabs-action-confluence-sync'
description: 'Action confluence sync that can be used to publish markdown documents to confluence.'
author: 'hadenlabs'
inputs:
  confluence_url:
    description: base url of confluence
    required: true
  confluence_username:
    description: confluence username
    required: true
  confluence_token:
    description: token of user
    required: true
  files:
    description: files to sync
    required: true

runs:
  using: 'composite'
  steps:
    - name: Sync files to confluence.
      uses: addnab/docker-run-action@v3
      with:
        image: kovetskiy/mark:latest
        options: -v ${{ github.workspace }}:/github/workspace --workdir /github/workspace
        run: |
          cp config.toml this-config.toml
          echo "username = '${{ inputs.confluence_username }}'" >> ./this-config.toml
          echo "password = '${{ inputs.confluence_token }}'" >> ./this-config.toml
          echo "base_url = '${{ inputs.confluence_url }}'" >> ./this-config.toml
          for file in ${{ inputs.files }}; do
            if ! grep -F "<!-- Space:" $file; then
                continue
            fi
            echo "> Sync $file";
            mark --config ./this-config.toml -f ${file} || exit 1;
            echo;
          done
          rm -rf this-config.toml
branding:
  icon: 'check-circle'
  color: 'green'
